@startuml Rule Engine Class Diagram
class Rule {
  -id: Integer
  -name: String
  -description: String
  -dateCreated: String
  -dateModified: String
  -createdBy: String
  -modifiedBy: String
}

class TenantConfig {
  -id: Integer
  -tenantId: String
  -configKey: String
  -configValue: String
}

class RuleCondition {
  -id: Integer
  -fieldName: String
  -operator: String
  -thresholdKey: String
  -thresholdType: String
}

class RuleAction {
  -id: Integer
  -outputKey: String
  -outputValue: String
}

Rule ||--o{ RuleCondition : has
Rule ||--o{ RuleAction : has
@enduml
