package rules;

import com.haifachagwey.ruleengine.model.GlobalFact;

global java.util.Map outputs;
global java.util.Map configs;
dialect "mvel"

//////////////////////////////////////////////////////
// Rule 1 - Default: operator handling
//////////////////////////////////////////////////////
rule "Car access - unknown LPN - operator"
salience 100
when
    $f : GlobalFact(
        properties["deviceType"] == "ENTRY" &&
        properties["carAccess"] == true
    )
then
    outputs.put("associatedAction", "INTERCOM");
    System.out.println("Unknown LPN → operator handling");
end

//////////////////////////////////////////////////////
// Rule 2 - Auto handling - no fuzzy match
//////////////////////////////////////////////////////
rule "Car access - no fuzzy candidate"
salience 90
when
    $f : GlobalFact(
        properties["deviceType"] == "ENTRY" &&
        properties["carAccess"] == true &&
        properties["autoHandling"] == true &&
        (
            properties["fuzzyEnabled"] == false ||
            (properties["fuzzyEnabled"] == true && properties["fuzzyMatchFound"] == false)
        )
    )
then
    outputs.put("associatedAction", "OPEN_BARRIER");
    outputs.put("financialAction", "CREATE_SHOWUP_PRODUCT");
    System.out.println("No fuzzy match → open barrier + showup");
end

//////////////////////////////////////////////////////
// Rule 3 - Auto handling - fuzzy match found
//////////////////////////////////////////////////////
rule "Car access - fuzzy candidate found"
salience 80
when
    $f : GlobalFact(
        properties["deviceType"] == "ENTRY" &&
        properties["carAccess"] == true &&
        properties["autoHandling"] == true &&
        properties["fuzzyEnabled"] == true &&
        properties["fuzzyMatchFound"] == true
    )
then
    outputs.put("associatedAction", "OPEN_BARRIER");
    outputs.put("financialAction", "REGISTERED_ENTRY");
    System.out.println("Fuzzy match → registered entry");
end
