package rules;

import com.haifachagwey.ruleengine.model.GlobalFact;

global java.util.Map outputs;
global java.util.Map configs;
dialect "mvel"

//////////////////////////////////////////////////////
// Rule 1 - Direct payment required
//////////////////////////////////////////////////////
rule "Contract parker expired - direct payment"
salience 30
when
    $f : GlobalFact(
        properties["deviceType"] == "EXIT" &&
        properties["productGroup"] == "CONTRACT" &&
        properties["productExpired"] == true &&
        properties["amount"] > configs["mediumAmountThreshold"]
    )
then
    outputs.put("associatedAction", "DIRECT_PAYMENT");
    System.out.println("Direct payment required");
end

//////////////////////////////////////////////////////
// Rule 2 - Later payment (invoice)
//////////////////////////////////////////////////////
rule "Contract parker expired - later payment"
salience 20
when
    $f : GlobalFact(
        properties["deviceType"] == "EXIT" &&
        properties["productGroup"] == "CONTRACT" &&
        properties["productExpired"] == true &&
        properties["amount"] > configs["lowAmountThreshold"] &&
        properties["amount"] <= configs["mediumAmountThreshold"]
    )
then
    outputs.put("Book amount", "LATER_PAYMENT");
    outputs.put("openBarrier", true);
end

//////////////////////////////////////////////////////
// Rule 3 - Lost revenue
//////////////////////////////////////////////////////
rule "Contract parker expired - lost revenue"
salience 10
when
    $f : GlobalFact(
        properties["deviceType"] == "EXIT" &&
        properties["productGroup"] == "CONTRACT" &&
        properties["productExpired"] == true &&
        properties["amount"] <= configs["lowAmountThreshold"]
    )
then
    outputs.put("associatedAction", "LOST_REVENUE");
    outputs.put("openBarrier", true);
end
