package rules;

import com.haifachagwey.ruleengine.model.GlobalFact;

global java.util.Map outputs;
global java.util.Map configs;
dialect "mvel"

//////////////////////////////////////////////////////
// Rule 1 - Default operator
//////////////////////////////////////////////////////
rule "Counter full - operator"
salience 100
when
    $f : GlobalFact(
        facts["deviceType"] == "ENTRY"
    )
then
    outputs.put("action", "INTERCOM");
    System.out.println("Counter issue → operator");
end

//////////////////////////////////////////////////////
// Rule 2 - Counter FULL + NORMAL mode
//////////////////////////////////////////////////////
rule "Counter full - overbook allowed"
salience 90
when
    $f : GlobalFact(
        facts["autoHandling"] == true &&
        facts["counterState"] == "FULL" &&
        facts["counterMode"] == "NORMAL"
    )
then
    outputs.put("action", "OPEN_BARRIER");
    outputs.put("counterAction", "OVERBOOK");
    System.out.println("Counter full → overbook");
end

//////////////////////////////////////////////////////
// Rule 3 - Counter FREE but car park FULL
//////////////////////////////////////////////////////
rule "Car park full"
salience 80
when
    $f : GlobalFact(
        facts["autoHandling"] == true &&
        facts["counterState"] == "FREE" &&
        facts["carParkFull"] == true
    )
then
    outputs.put("action", "INTERCOM");
    System.out.println("Car park full → stop customer");
end

//////////////////////////////////////////////////////
// Rule 4 - Counter BLOCKED
//////////////////////////////////////////////////////
rule "Counter blocked"
salience 70
when
    $f : GlobalFact(
        facts["autoHandling"] == true &&
        facts["counterState"] == "BLOCKED"
    )
then
    outputs.put("action", "INTERCOM");
    System.out.println("Counter blocked → stop customer");
end
