package rules

import com.haifachagwey.ruleengine.model.OrderRequest
import com.haifachagwey.ruleengine.model.OrderDiscount

global OrderDiscount orderDiscount;

rule "Discount for orders"
    when
        $order : OrderRequest(age < 18)
    then
        double discount = 20;
        orderDiscount.setDiscount(discount);
        System.out.println("Applied 20% discount for order from customer under 18 years old.");
end

