package rules;

import com.haifachagwey.ruleengine.model.GlobalFact;

global java.util.Map outputs;
global java.util.Map configs;
dialect "mvel"

//////////////////////////////////////////////////////
// Rule 1 - Default operator
//////////////////////////////////////////////////////
rule "Access profile - operator"
salience 100
when
    $f : GlobalFact(
        facts["deviceType"] == "ENTRY" &&
        facts["carAccess"] == true
    )
then
    outputs.put("action", "INTERCOM");
    System.out.println("Out of profile → operator");
end

//////////////////////////////////////////////////////
// Rule 2 - Grace time violated → allow
//////////////////////////////////////////////////////
rule "Access profile - grace time violated"
salience 90
when
    $f : GlobalFact(
        facts["autoHandling"] == true &&
        facts["graceTimeViolated"] == true
    )
then
    outputs.put("action", "OPEN_BARRIER");
    outputs.put("financialAction", "OUT_OF_PROFILE_ENTRY");
    System.out.println("Grace time violated → allow entry with special product");
end
